name: CKC Indy
on:
  push

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - name: Log in to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push the image
        run: |
          docker build . --tag ghcr.io/jacobmcollins/ckcindy:latest
          docker push ghcr.io/jacobmcollins/ckcindy:latest